DROP TABLE MOVIE IF EXISTS;

CREATE TABLE MOVIE (
    ID SERIAL PRIMARY KEY,
    TITLE TEXT,
    VOTE_AVERAGE DOUBLE,
    VOTE_COUNT INTEGER,
    RELEASE_DATE VARCHAR(50),
    REVENUE BIGINT,
    RUNTIME INTEGER,
    BACKDROP_PATH TEXT,
    BUDGET BIGINT,
    HOMEPAGE TEXT,
    OVERVIEW CLOB,
    POPULARITY DOUBLE,
    POSTER_PATH TEXT,
    GENRES CHARACTER VARYING ARRAY
);
